name: Deploy to Remote Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: SSH and execute commands
        run: |
          PASSWORD=${{ secrets.SSH_PASSWORD }}  # Store your password in GitHub secrets
          HOST="194.238.22.108"
          USER="root"

          /usr/bin/expect -c "
          set timeout 10
          spawn ssh $USER@$HOST
          expect \"*?assword:*\" { send \"$PASSWORD\r\" }
          expect \"*#\" { send \"cd /var/www/one-build-cms\r\" }
          expect \"*#\" { send \"git pull\r\" }
          expect \"*#\" { send \"npm install\r\" }
          expect \"*#\" { send \"npm run build\r\" }
          expect eof
          "
