name: SSH Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the OS if needed

    steps:
      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: SSH and execute commands
        run: |
          HOST="194.238.22.108"
          USER="root"
          PASSWORD=${{ secrets.SSH_PASSWORD }}  # Access the stored password

          /usr/bin/expect -c "
          set timeout -1  # Set to -1 to wait for command completion indefinitely
          # Start the SSH connection
          spawn ssh $USER@$HOST
          expect {
            # Handle the password prompt
            \"*?assword:*\" { send \"$PASSWORD\r\" }
            # Handle the authenticity prompt
            \"*Are you sure you want to continue connecting (yes/no)?*\" {
              send \"yes\r\"
              exp_continue
            }
            # In case of a new key fingerprint prompt
            \"*ED25519 key fingerprint is*\" {
              send \"yes\r\"
              exp_continue
            }
          }
          # Navigate to the directory and run commands
          expect \"*#\" { send \"cd /var/www/one-build-cms\r\" }
          expect \"*#\" { send \"git pull\r\" }
          expect \"*#\" { send \"npm install\r\" }
          
          # Run the build process and wait for it to complete
          expect \"*#\" { send \"npm run build\r\" }

          # Ensure the process waits for completion
          expect {
            \"*#\" { send \"exit\r\" }
            eof
          }
          "
