name: SSH Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the OS if needed

    steps:
      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: SSH and execute commands
        run: |
          HOST="194.238.22.108"
          USER="root"
          PASSWORD=${{ secrets.SSH_PASSWORD }}  # Access the stored password

          /usr/bin/expect << EOF
          # Start the SSH connection
          spawn ssh $USER@$HOST "bash -l"
          expect {
            "*?assword:*" { send "$PASSWORD\r" }
            "*Are you sure you want to continue connecting (yes/no)?*" {
              send "yes\r"
              exp_continue
            }
            "*ED25519 key fingerprint is*" {
              send "yes\r"
              exp_continue
            }
          }

          # Navigate to the directory and run commands immediately without waiting for completion
          send "cd /var/www/one-build-cms\r"
          send "git pull\r"
          send "npm install\r"
          send "npm run build\r"
          send "apt install && apt update -y\r"

          expect eof
          EOF
